apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gz2qr54wr-nodejs 
  janus-idp.io/tekton: gz2qr54wr-nodejs
  backstage.io/kubernetes-id: gz2qr54wr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gz2qr54wr-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  